[package]
name = "workshop"
version = "0.1.0"
edition = "2021"

[dependencies]
geo = "0.29.3"
itertools = "0.13.0"
mimalloc = "0.1.43"
nannou = "0.19.0"
nannou_egui = "0.19.0"
petgraph = "0.6.5"

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"
strip = "debuginfo"
