[package]
name = "workshop"
version = "0.1.0"
edition = "2021"

[dependencies]
mimalloc = "0.1.43"
nannou = "0.19.0"
rayon = "1.10.0"

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"
strip = "debuginfo"
